export const dbTask = [
  {
    title: "Redo Portfolio",
    label: "study",
    colorScheme: "blue",
    avatarUrl: "male",
    action: "todo",
  },
  {
    title: "Task 1",
    label: "bank",
    colorScheme: "blue",
    avatarUrl: "male",
    action: "todo",
  },
  {
    title: "Task 1",
    label: "bank",
    colorScheme: "blue",
    avatarUrl: "male",
    action: "todo",
  },
  {
    title: "Task 2",
    label: "bank",
    colorScheme: "blue",
    avatarUrl: "female",
    action: "todo",
  },
  {
    title: "Redo Portfolio",
    label: "study",
    colorScheme: "orange",
    avatarUrl: "male",
    action: "inProgress",
  },
  {
    title: "Task 1",
    label: "bank",
    colorScheme: "orange",
    avatarUrl: "male",
    action: "inProgress",
  },
  {
    title: "Task 2",
    label: "bank",
    colorScheme: "orange",
    avatarUrl: "female",
    action: "inProgress",
  },
  {
    title: "Redo Portfolio",
    label: "study",
    colorScheme: "purple",
    avatarUrl: "male",
    action: "review",
  },
  {
    title: "Task 1",
    label: "bank",
    colorScheme: "purple",
    avatarUrl: "male",
    action: "review",
  },
  {
    title: "Task 2",
    label: "bank",
    colorScheme: "purple",
    avatarUrl: "female",
    action: "review",
  },
  {
    title: "Redo Portfolio",
    label: "study",
    colorScheme: "green",
    avatarUrl: "male",
    action: "done",
  },
  {
    title: "Task 1",
    label: "bank",
    colorScheme: "green",
    avatarUrl: "male",
    action: "done",
  },
  {
    title: "Task 2",
    label: "bank",
    colorScheme: "green",
    avatarUrl: "female",
    action: "done",
  },
];
